id: PB94F36D6
initial_creation_type: input
source_metadata:
  title: Butön Rinchen Drup Series
  language: bo
  description: 'Texts by and about the great Sakya lama Butön Rinchen Drup (bu ston
    rin chen grub, 1290–1364) of Shalu Monastery:'
  volume:
    73cb711cf7c149a096e6d839ba1ef3b8:
      title: Advice in Three Sets of Three
      parent: Advice
    dc925ec9fb4848c3b74b1a7a6a22c131:
      title: 'A Beautiful Lotus Garland: In Praise of the Omniscient Lord of Dharma
        Butön Rinchen Drup'
      parent: Praise
    fffa04cc552e4afaa3f27b571656c44e:
      title: Prayer to Butön Rinpoche
      parent: Prayers
created_at: '2022-02-28T22:41:10.331440'
last_modified_at: '2022-02-28T22:41:10.331443'
